Repository agonzalezbesada/Chess_awt, pull requests merged in 2023-05, with the labels that each got.

#1 Agonzalezbesada
  src/Modelo/Alfil.java
  src/Modelo/Caballo.java
  src/Modelo/Modelo.java
  src/Modelo/Peon.java
  src/Modelo/Pieza.java
  src/Modelo/Reina.java
  src/Modelo/Rey.java
  src/Modelo/Torre.java
Labels: enhancement

#6 Tablero inicializado
  src/Controlador/Controlador.java
  src/Modelo/Alfil.java
  src/Modelo/Caballo.java
  src/Modelo/Modelo.java
  src/Modelo/Peon.java
  src/Modelo/Pieza.java
  src/Modelo/Reina.java
  src/Modelo/Rey.java
  src/Modelo/Torre.java
  src/Vista/DesplazamientoRaton.java
  src/Vista/EleccionRaton.java
  src/Vista/MenuTablero.java
  src/Vista/Vista.java
Labels: enhancement

#7 Documentacion + borrado clases innecesarias
  src/Controlador/Controlador.java
  src/Modelo/Alfil.java
  src/Modelo/Caballo.java
  src/Modelo/IPieza.java
  src/Modelo/Modelo.java
  src/Modelo/Peon.java
  src/Modelo/Pieza.java
  src/Modelo/Reina.java
  src/Modelo/Rey.java
  src/Modelo/Tablero.java
  src/Modelo/Torre.java
  src/Vista/ManejadorRaton.java
  src/Vista/MenuPrincipal.java
  src/Vista/MenuTablero.java
  src/Vista/Vista.java
Labels: documentation

#10 Seguimiento_03_23
  src/Controlador/Controlador.java
  src/Modelo/Alfil.java
  src/Modelo/Caballo.java
  src/Modelo/IPieza.java
  src/Modelo/Modelo.java
  src/Modelo/Peon.java
  src/Modelo/Pieza.java
  src/Modelo/Reina.java
  src/Modelo/Rey.java
  src/Modelo/Torre.java
  src/Vista/ManejadorRaton.java
  src/Vista/MenuPrincipal.java
  src/Vista/MenuTablero.java
  src/Vista/Vista.java
Labels: documentation, enhancement

#11 Temporizador
  src/Vista/MenuPrincipal.java
  src/Vista/MenuTablero.java
Labels: enhancement

#12 Comer
  src/Controlador/Controlador.java
  src/Modelo/Alfil.java
  src/Modelo/Caballo.java
  src/Modelo/IPieza.java
  src/Modelo/Modelo.java
  src/Modelo/Peon.java
  src/Modelo/Pieza.java
  src/Modelo/Reina.java
  src/Modelo/Rey.java
  src/Modelo/Torre.java
Labels: enhancement

#17 Autómata añadido
  src/Modelo/Automata.java
  src/Modelo/Movimiento.java
  src/Vista/MenuTablero.java
Labels: enhancement

#18 Colisiones intermedias
  src/Controlador/Controlador.java
  src/Modelo/Alfil.java
  src/Modelo/Modelo.java
  src/Modelo/Peon.java
  src/Modelo/Pieza.java
  src/Modelo/Torre.java
  src/Vista/MenuTablero.java
Labels: enhancement

#19 Seguimiento_04_23
  src/Controlador/Controlador.java
  src/Modelo/Alfil.java
  src/Modelo/Automata.java
  src/Modelo/Caballo.java
  src/Modelo/IPieza.java
  src/Modelo/Modelo.java
  src/Modelo/Movimiento.java
  src/Modelo/Peon.java
  src/Modelo/Pieza.java
  src/Modelo/Reina.java
  src/Modelo/Rey.java
  src/Modelo/Torre.java
  src/Vista/MenuPrincipal.java
  src/Vista/MenuTablero.java
  src/Vista/Vista.java
Labels: enhancement

#23 close #22
  src/Vista/MenuTablero.java
Labels: bug

#28 Observer + BD + Ficheros
  src/Controlador/Controlador.java
  src/Modelo/BD.java
  src/Modelo/Guardado.java
  src/Modelo/Jugador.java
  src/Modelo/Modelo.java
  src/Modelo/Partida.java
  src/Vista/MenuTablero.java
Labels: enhancement

#29 Seguimiento_05_23
  src/.idea/.gitignore
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/vcs.xml
  src/Controlador/Controlador.java
  src/Controlador/ObserverMovimientos.java
  src/Modelo/Alfil.java
  src/Modelo/Automata.java
  src/Modelo/BD.java
  src/Modelo/Guardado.java
  src/Modelo/Jugador.java
  src/Modelo/Modelo.java
  src/Modelo/Movimiento.java
  src/Modelo/Partida.java
  src/Modelo/Peon.java
  src/Modelo/Reina.java
  src/Modelo/Rey.java
  src/Modelo/Torre.java
  src/Proyecto.iml
  src/Vista/MenuTablero.java
  src/out/production/Proyecto/.idea/.gitignore
  src/out/production/Proyecto/.idea/misc.xml
  src/out/production/Proyecto/.idea/modules.xml
  src/out/production/Proyecto/.idea/vcs.xml
  src/out/production/Proyecto/Controlador/Controlador.class
  src/out/production/Proyecto/Modelo/Alfil.class
  src/out/production/Proyecto/Modelo/Caballo.class
  src/out/production/Proyecto/Modelo/IPieza.class
  src/out/production/Proyecto/Modelo/Modelo.class
  src/out/production/Proyecto/Modelo/Peon.class
  src/out/production/Proyecto/Modelo/Pieza.class
  src/out/production/Proyecto/Modelo/Reina.class
  src/out/production/Proyecto/Modelo/Rey.class
  src/out/production/Proyecto/Modelo/Tablero.class
  src/out/production/Proyecto/Modelo/Torre.class
  src/out/production/Proyecto/Proyecto.iml
  src/out/production/Proyecto/Vista/ManejadorRaton.class
  src/out/production/Proyecto/Vista/MenuPrincipal$1.class
  src/out/production/Proyecto/Vista/MenuPrincipal$2.class
  src/out/production/Proyecto/Vista/MenuPrincipal.class
  src/out/production/Proyecto/Vista/MenuTablero$1.class
  src/out/production/Proyecto/Vista/MenuTablero$2.class
  src/out/production/Proyecto/Vista/MenuTablero.class
  src/out/production/Proyecto/Vista/Vista.class
Labels: documentation, enhancement

#31 Eliminacion Carpetas Sobrantes
  src/.idea/.gitignore
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/vcs.xml
  src/Proyecto.iml
  src/out/production/Proyecto/.idea/.gitignore
  src/out/production/Proyecto/.idea/misc.xml
  src/out/production/Proyecto/.idea/modules.xml
  src/out/production/Proyecto/.idea/vcs.xml
  src/out/production/Proyecto/Controlador/Controlador.class
  src/out/production/Proyecto/Modelo/Alfil.class
  src/out/production/Proyecto/Modelo/Caballo.class
  src/out/production/Proyecto/Modelo/IPieza.class
  src/out/production/Proyecto/Modelo/Modelo.class
  src/out/production/Proyecto/Modelo/Peon.class
  src/out/production/Proyecto/Modelo/Pieza.class
  src/out/production/Proyecto/Modelo/Reina.class
  src/out/production/Proyecto/Modelo/Rey.class
  src/out/production/Proyecto/Modelo/Tablero.class
  src/out/production/Proyecto/Modelo/Torre.class
  src/out/production/Proyecto/Proyecto.iml
  src/out/production/Proyecto/Vista/ManejadorRaton.class
  src/out/production/Proyecto/Vista/MenuPrincipal$1.class
  src/out/production/Proyecto/Vista/MenuPrincipal$2.class
  src/out/production/Proyecto/Vista/MenuPrincipal.class
  src/out/production/Proyecto/Vista/MenuTablero$1.class
  src/out/production/Proyecto/Vista/MenuTablero$2.class
  src/out/production/Proyecto/Vista/MenuTablero.class
  src/out/production/Proyecto/Vista/Vista.class
Labels: bug, duplicate
